import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

/**
 Each key has a given set of permissions on the API routes.
 Used for authorization when making calls to a protected Meilisearch instance.
 */
public struct Key: Codable, Equatable {
  // MARK: Properties

  /// A uuid v4 to identify the API key.
  public let uid: String
  /// A human-readable name for the key.
  public let name: String?
  /// A description for the key.
  public let description: String?
  /// An alphanumeric key value generated by Meilisearch by hashing the uid and the master key on API key creation.
  public let key: String
  /// An array of API actions permitted for the key.
  public let actions: [String]
  /// An array of strings (indexes names) the key is authorized to act on.
  public let indexes: [String]
  /// Date and time when the key will expire, represented in RFC 3339 format.
  public let expiresAt: String?
  /// Date and time when the key was created, represented in RFC 3339 format.
  public let createdAt: String
  /// Date and time when the key was last updated, represented in RFC 3339 format.
  public let updatedAt: String
}
