name: MeiliSearch swift test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.2.4' # This value is passed to swiftenv without modification. 
    - name: Docker setup
      run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key='masterKey'
    - name: Test
      run: |
        swift test